### ISSUE TITLE
👨‍💻 Add Rect.Js Projects

### ISSUE THREAD

**Issue by sudo-parnab** [sudo-parnab/Its-webtober#12]
Follow the guidelines and add some react.js projects

**Comment by Lavin-Valechha** [comment]
Please Assign this issue to me @sudo-parnab

**Comment by sudo-parnab** [comment]
Go ahead, join the WhatsApp group

**Comment by sudo-parnab** [comment]
@Lavin-Valechha what's the status?

**Comment by Lavin-Valechha** [comment]
Sorry ig there was a confusion regarding similar type issues because i already committed in your repository?

**Comment by sudo-parnab** [comment]
yes, that's why this issue is closed
