### ISSUE TITLE
👨‍💻 Add a MERN Project

### ISSUE THREAD

**Issue by sudo-parnab** [sudo-parnab/Its-webtober#13]
Follow the guidelines and add a MERN project

**Comment by farhan-sayeed** [comment]
@sudo-parnab Could you pls assign me this issue to work on

**Comment by sudo-parnab** [comment]
@farhan-sayeed go ahead and join the WhatsApp group

**Comment by sudo-parnab** [comment]
@farhan-sayeed what's the status?

**Comment by farhan-sayeed** [comment]
@sudo-parnab working on it

**Comment by farhan-sayeed** [comment]
@sudo-parnab Raised PR for the same, pls add the `hactoberfest` related labels before merging
