### ISSUE TITLE
⬆ Modify any existing project

### ISSUE THREAD

**Issue by sudo-parnab** [sudo-parnab/Its-webtober#14]
Follow the guidelines and update or modify any existing project

**Comment by farhan-sayeed** [comment]
@sudo-parnab Could you assign me this issue to work on

**Comment by sudo-parnab** [comment]
@farhan-sayeed go ahead and join the WhatsApp group

**Comment by sudo-parnab** [comment]
@farhan-sayeed what's the status?

**Comment by Sayanjones** [comment]
@sudo-parnab kindly assign me this issue.
