### ISSUE TITLE
✒ Add issue Templates

### ISSUE THREAD

**Issue by sudo-parnab** [sudo-parnab/Its-webtober#15]
Follow the guidelines and add 2 issue templates
* 👨‍💻 New project
* 🐛 Bug Found

**Comment by sudo-parnab** [comment]
@tmsagarofficial go ahead brother

**Comment by sudo-parnab** [comment]
@tmsagarofficial join the WhatsApp group

**Comment by sudo-parnab** [comment]
@tmsagarofficial what's the status now?

**Comment by Parnab03** [comment]
assign it to me

**Comment by sudo-parnab** [comment]
@Parnab03 go ahead
