### ISSUE TITLE
Adding contributor section 

### ISSUE THREAD

**Issue by shravya312** [sudo-parnab/Its-webtober#2]

**Comment by sudo-parnab** [comment]
Hi @shravya312, please elaborate what you want to specified ?

**Comment by shravya312** [comment]
Adding images of all the contributors

**Comment by Parnab03** [comment]
Ok sure, join the WhatsApp group.

**Comment by shravya312** [comment]
![image](https://github.com/user-attachments/assets/d5fc7f00-b077-4dc8-aa23-5619675291e4)

**Comment by shravya312** [comment]
can u assign the issue to me @sudo-parnab

**Comment by shravya312** [comment]
joined the whatsapp group

**Comment by sudo-parnab** [comment]
> can u assign the issue to me @sudo-parnab 

Yes not a problem

**Comment by sudo-parnab** [comment]
> joined the whatsapp group

Ok fine, elaborate your concern there, happy coding

**Comment by shravya312** [comment]
Okay 👍

**Comment by sudo-parnab** [comment]
@shravya312 in readme.md file's contribution section new contributions are not updated fix this issue, your own contribution is not updated yet.

**Comment by shravya312** [comment]
I checked it.code is working it is connected to the contributors graph 
this is the code used I will share it here
<a href="https://github.com/sudo-parnab/Its-webtober/graphs/contributors"> 
<img src="https://contrib.rocks/image?repo=sudo-parnab/Its-webtober" /> </a><br>

**Comment by shravya312** [comment]
Uploading sudo-parnab_Its-webtober_ Contribute to open-source web development projects during Hacktoberfest. Ideal for beginners. Join the community and level up your skills. - Google Chrome 2024-10-06 13-10-11.mp4…

**Comment by shravya312** [comment]
https://github.com/user-attachments/assets/bf9b54b1-9410-461a-bbec-b89081d4e9ad

**Comment by sudo-parnab** [comment]
checkout why it is not showing in readme.md. if it not working properly try to change that component

**Comment by shravya312** [comment]
Okay 👍 I will check for alternatives...

**Comment by sudo-parnab** [comment]
how is it going?

**Comment by shravya312** [comment]
I got to know another method which have to be implemented manually

**Comment by shravya312** [comment]
Will I implement?

**Comment by sudo-parnab** [comment]
yes if it works, then implement

**Comment by shravya312** [comment]
Each time it won't automatically update

**Comment by shravya312** [comment]
We have to update the code each time

**Comment by sudo-parnab** [comment]
that's a big problem
delete this code from readme.md and submit a PR, work on some other issue

**Comment by shravya312** [comment]
Okay 👍
