### ISSUE TITLE
👀 Add DSA and Code

### ISSUE THREAD

**Issue by sudo-parnab** [sudo-parnab/Its-webtober#23]
Visit the repository at https://github.com/sudo-parnab/Its-algober and add programming language files such as C, Python, Java, or any other language as per the project's requirements. Make sure to follow proper naming conventions and include well-documented code snippets or algorithms related to the repository theme.

**Comment by farhan-sayeed** [comment]
@sudo-parnab Do we require to raise an issue there by our own?

**Comment by sudo-parnab** [comment]
> @sudo-parnab Do we require to raise an issue there by our own?
Yes
