### ISSUE TITLE
Feature Add 

### ISSUE THREAD

**Issue by Sayanjones** [sudo-parnab/Its-webtober#34]
### 🔖 Feature Description

The primary change in this PR involves updating the image in the README file. The updated image provides a clearer and more accurate representation of the current state of the project. This change ensures that the README reflects the latest UI and visual elements of the project, making it easier for users to understand its functionality and appearance.

### 📈 Benefits

The benefits of updating the image in the README file are significant in improving the overall user experience and project clarity. A clear and accurate visual representation helps potential users and contributors quickly grasp the project's functionality and current design. By aligning the README with the actual state of the project, it enhances transparency and reduces confusion. This update also ensures that first impressions are positive, as users can better visualize how the project looks and operates.

### 📷 Screenshots

![image](https://github.com/user-attachments/assets/9a6fa578-02b5-4584-8d93-6c63a7369388)

### ✔️ Checklist

- [X] I have checked the existing issues to avoid duplicates.
- [X] I have read and understood the [Contributing Guidelines](https://github.com/sudo-parnab/Its-algober/blob/main/CONTRIBUTING.md).
- [X] I have read and agree to the [Code of Conduct](https://github.com/sudo-parnab/Its-algober/blob/main/CODE_OF_CONDUCT.md).
- [X] I am a Hacktoberfest'24 contributor.
- [X] I am willing to work on this issue.

**Comment by sudo-parnab** [comment]
Go ahead @Sayanjones
